language: r
os: osx
cache: packages
r:
- 3.2
- 3.3
- 3.4
- oldrel
- release
# CRAN doesn't host macOS binary packages for r-devel
# - devel
env:
  LOCAL_AUTOBREW: "TRUE"
  TEST_R_WITH_ARROW: "TRUE"
  BINTRAY_APIKEY:
    secure: bkUqt4D1L4FgIlWCIBSzulHnG+Id8xE5amFKd5BKVj123YhMsY3q/smKYs4SLU6cj7MhNLQmiyVAp0FXdPqeAaDDn56eKIGqaiMAiS6F0UWHBo1YX9F1H6ScMfGxEAn27mNTH3CsiB9w9vICzjJxG9Aaps0O/whmY7J5z4KE1rLc/2KhNHuuTpVUGoRupnsYqNAew0Y7Dx1mquIQuSq2OrAMKT1iPLgvAmXhDg/aC2iwOEewFalDalYaTbV3IkfnZZU4JJ/BUYhT459uLLdxJdZziI0C1hPfYa+jWclFwRzDCzT+3FAJXwDFM1lwXvdT1oAFAkCyKTXXx9q8R2W3Cl4S+ymhL9tw75Z4lo4EHVpeTD/qK5w3OhkPs5IQp4hAjFEx6CrRYJVPD0rBnd2qEOrBzgUvw3E1/zeQdL6tsPfqC5YvTb5Ow+Q66ZXvwlEhGCEy5A2tRtCLjSs8pRk+6wPyDNthu9NhSJDTXi97Yite6LTzOnV33cZpzTAGSFYlidMFQJg/VjLhNXeTD76tWb0IMAEEpfQyWMM7VdgfmMXDaLECKgtXpIUg2QlQ4W1hrFjlt0Y9KD6Pdvw1CXr2FO2TeIPAnXVc4rwzg4Pyh9hXRQFdtWw5e6y0edcFFUgpqqW3kTHXHyTKJQ6emKCz+2Yhh4m3HMg4fwMokBZMu5g=
before_install:
- git clone --depth=1 https://github.com/apache/arrow.git
- cd arrow/r
- source ../../up-date-description.sh
script:
# Use a custom "script" to add travis_wait in order to prevent build timeouts
- R CMD build .
- travis_wait R CMD check arrow_*.tar.gz --as-cran --install-args="--build"
after_success:
- test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
- source ../../bintray-upload.sh
