language: r
os: osx
cache: packages
r:
# Installation of older R versions fails:
# 'installer: Certificate used to sign package is not trusted. Use -allowUntrusted to override.'
# - 3.0
# - 3.1
- 3.2
- 3.3
- 3.4
- oldrel
- release
# CRAN doesn't host macOS binary packages for r-devel
# - devel
r_check_args: '--as-cran --install-args="--build"'
env:
  LOCAL_AUTOBREW: "TRUE"
  TEST_R_WITH_ARROW: "TRUE"
before_install:
- git clone --depth=1 https://github.com/nealrichardson/arrow -b nightly-r
- cd arrow/r
- source ../../up-date-description.sh
after_success:
- test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
before_deploy:
- Rscript -e 'tools::write_PACKAGES(".", type = "mac.binary")'
- cd ../../
- source up-date-bintray.sh
deploy:
  provider: bintray
  file: bintray.json
  user: nealrichardson
  skip_cleanup: true
  key:
    secure: bkUqt4D1L4FgIlWCIBSzulHnG+Id8xE5amFKd5BKVj123YhMsY3q/smKYs4SLU6cj7MhNLQmiyVAp0FXdPqeAaDDn56eKIGqaiMAiS6F0UWHBo1YX9F1H6ScMfGxEAn27mNTH3CsiB9w9vICzjJxG9Aaps0O/whmY7J5z4KE1rLc/2KhNHuuTpVUGoRupnsYqNAew0Y7Dx1mquIQuSq2OrAMKT1iPLgvAmXhDg/aC2iwOEewFalDalYaTbV3IkfnZZU4JJ/BUYhT459uLLdxJdZziI0C1hPfYa+jWclFwRzDCzT+3FAJXwDFM1lwXvdT1oAFAkCyKTXXx9q8R2W3Cl4S+ymhL9tw75Z4lo4EHVpeTD/qK5w3OhkPs5IQp4hAjFEx6CrRYJVPD0rBnd2qEOrBzgUvw3E1/zeQdL6tsPfqC5YvTb5Ow+Q66ZXvwlEhGCEy5A2tRtCLjSs8pRk+6wPyDNthu9NhSJDTXi97Yite6LTzOnV33cZpzTAGSFYlidMFQJg/VjLhNXeTD76tWb0IMAEEpfQyWMM7VdgfmMXDaLECKgtXpIUg2QlQ4W1hrFjlt0Y9KD6Pdvw1CXr2FO2TeIPAnXVc4rwzg4Pyh9hXRQFdtWw5e6y0edcFFUgpqqW3kTHXHyTKJQ6emKCz+2Yhh4m3HMg4fwMokBZMu5g=
