language: r
os: osx
cache: packages
r:
- 3.2
- 3.3
- 3.4
- oldrel
- release
# CRAN doesn't host macOS binary packages for r-devel
# - devel
env:
  LOCAL_AUTOBREW: "TRUE"
  TEST_R_WITH_ARROW: "TRUE"
before_install:
- git clone --depth=1 https://github.com/apache/arrow.git
- cd arrow/r
- source ../../up-date-description.sh
script:
# Use a custom "script" to add travis_wait in order to prevent build timeouts
- travis_wait R CMD build .
- travis_wait R CMD check arrow_*.tar.gz --as-cran --install-args="--build"
after_success:
- test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::codecov()'
- source ../../bintray-upload.sh
