# Copied from https://github.com/krlmlr/r-appveyor/blob/master/sample.appveyor.yml

environment:
  TEST_R_WITH_ARROW: TRUE
  RWINLIB_LOCAL: '%APPVEYOR_BUILD_FOLDER%\libarrow.zip'
  RVERSION: "3.6"

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  - git clone --depth=1 https://github.com/apache/arrow.git
  - mkdir ci
  - copy arrow\ci\PKGBUILD ci\
  - copy arrow\ci\appveyor-build-r.sh ci\
  - copy arrow\ci\windows-pkg-arrow-for-r.sh ci\
  - xcopy /S /I arrow\cpp cpp
  - xcopy /S /I arrow\format format
  - xcopy /S /I arrow\r r
  - cd r
  # TODO: fix the next line, it didn't work
  # - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/up-date-description.sh"
  - ps: Bootstrap
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  # - rmdir /s /Q C:\OpenSSL-Win32 C:\OpenSSL-Win64
  # - C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  # - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci/appveyor-build-r.sh"
  - ps: echo '@bash.exe test.sh %*' | Out-File -Encoding ASCII .\test.sh.cmd
  - test.sh
  - pushd r
  # - travis-tool.sh install_deps

test_script:
  # - travis-tool.sh run_tests
  # TODO: this didn't work
  # - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/write-PACKAGES-win.sh"
  - dir
  - dir %APPVEYOR_BUILD_FOLDER%

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: 'r\*.Rcheck\**\*.log'
    name: Logs

  - path: 'r\*.Rcheck\**\*.out'
    name: Logs

  - path: 'r\*.Rcheck\**\*.fail'
    name: Logs

  - path: 'r\*.Rcheck\**\*.Rout'
    name: Logs

  - path: 'r\*_*.tar.gz'
    name: Source

  - path: 'r\*_*.zip'
    name: Binary

  - path: 'r\PACKAGES*'
    name: Binary

  - path: 'r\test.txt'
    name: Binary

deploy:
  # TODO: how to specify destination path
  - provider: BinTray
    username: nealrichardson
    subject: nealrichardson
    repo: "arrow-r/bin/windows/contrib/${RVERSION}"
    package: arrow
    version: latest
    publish: true
    override: true
    api_key:
      secure: Jdipuo3I2KJCbAT5kZ/OWKdhbQro7ebfkN87Gd4aZ74ku2orToy7MR+EqRZddzzn
    on:
      branch: master
    artifact: Binary
