# Cf. https://github.com/apache/arrow/blob/master/appveyor.yml

environment:
  global:
    TEST_R_WITH_ARROW: TRUE
    RWINLIB_LOCAL: '%APPVEYOR_BUILD_FOLDER%\libarrow.zip'
    BINTRAY_USER: "nealrichardson"
    BINTRAY_APIKEY:
      secure: Jdipuo3I2KJCbAT5kZ/OWKdhbQro7ebfkN87Gd4aZ74ku2orToy7MR+EqRZddzzn
  matrix:
    - R_VERSION: 3.0.3
      PKGTYPE: both
      CRAN: http://cloud.r-project.org/
    - R_VERSION: 3.1.3
      PKGTYPE: both
      CRAN: http://cloud.r-project.org/
    - R_VERSION: 3.2.5
      PKGTYPE: both
    - R_VERSION: 3.3.3
      PKGTYPE: both
    - R_VERSION: 3.4.4
    - R_VERSION: 3.5.3
    - R_VERSION: release
    - R_VERSION: devel

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  - git clone --depth=1 https://github.com/nealrichardson/arrow -b nightly-r
  # - git clone --depth=1 https://github.com/apache/arrow.git
  # The build scripts in apache/arrow assume that they're in a specific location
  # so we need to copy certain files up a level
  - mkdir ci
  - copy arrow\ci\PKGBUILD ci\
  - copy arrow\ci\appveyor-build-r.sh ci\
  - copy arrow\ci\windows-pkg-arrow-for-r.sh ci\
  - xcopy /S /I arrow\cpp cpp
  - xcopy /S /I arrow\format format
  - xcopy /S /I arrow\r r
  - cd r
  - ps: Bootstrap
  # Turn these bash scripts into things that are executable
  - ps: echo '@bash.exe ../rscript.sh %*' | Out-File -Encoding ASCII .\rscript.sh.cmd
  - ps: echo '@bash.exe ../bintray-win-upload.sh %*' | Out-File -Encoding ASCII .\upload.sh.cmd
  - ps: echo '@bash.exe ../up-date-description.sh %*' | Out-File -Encoding ASCII .\up-date-description.sh.cmd
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - pushd r
  - travis-tool.sh install_deps
  - popd
  - rmdir /s /Q C:\OpenSSL-Win32 C:\OpenSSL-Win64
  - C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --refresh --sysupgrade --sysupgrade
  - C:\msys64\usr\bin\bash --login -c "$(cygpath ${APPVEYOR_BUILD_FOLDER})/ci/appveyor-build-r.sh"
  - pushd r
  # Add today's date as the patch version for the R package
  - up-date-description.sh

test_script:
  - travis-tool.sh run_tests
  # Write the PACKAGES manifest
  - rscript.sh 'tools::write_PACKAGES(".", type="win.binary")'

on_failure:
  - travis-tool.sh dump_logs

on_success:
  # Push to bintray
  - upload.sh PACKAGES
  - upload.sh PACKAGES.gz
  - upload.sh PACKAGES.rds
  - upload.sh arrow*.zip

artifacts:
  - path: 'r\*.Rcheck\**\*.log'
    name: Logs

  - path: 'r\*.Rcheck\**\*.out'
    name: Logs

  - path: 'r\*.Rcheck\**\*.fail'
    name: Logs

  - path: 'r\*.Rcheck\**\*.Rout'
    name: Logs

  - path: 'r\*_*.tar.gz'
    name: Source

  - path: 'r\*_*.zip'
    name: Binary

  - path: 'r\PACKAGES*'
    name: Binary
